### ISSUE TITLE
first-timers-only: Add test to verify addConfirm's options supports class attribute

### ISSUE THREAD

**Issue by TalAter** [TalAter/Progressive-UI-KITT#1]
This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Thank you for your help :heart:
#### Background

Progressive UI KITT makes it easy to add a GUI to progressive web apps.

For example, by running the following you can display a message to the user.

``` javascript
ProgressiveKITT.addMessage('Offline. Changes you make will be saved for later');
```

KITT's latest version now allows the developer to pass a class name when adding a new message. This class will then be added to the classList of that message's div.

``` javascript
ProgressiveKITT.addMessage('Offline. Changes you make will be saved for later', {class: 'progressivekitt-message--offline'});
```

![addmessage-classy](https://cloud.githubusercontent.com/assets/926653/18037549/f1cbfbac-6d8f-11e6-906a-a5c3db0d1de5.gif)

You can read the [addMessage() API docs](https://github.com/TalAter/Progressive-UI-KITT/blob/master/docs/API.md#addmessagestring-object).
#### The Issue

KITT strives for 100% coverage with automated tests. While the existing test specs do test that the functionality of `ProgressiveKITT.addMessage()` works with a class, it does not currently test to verify that it is also correctly supported by `addAlert()`.

`addAlert()` is similar to `addMessage()` but it also adds a button to the message. It accepts the options object as its fourth argument (after the alert's text, the button label, and a callback function).

``` javascript
ProgressiveKITT.addAlert('Offline. Changes you make will be saved for later', 'Got it!', function() {console.log('Aha');}, {class: 'progressivekitt-message--offline'});
```

![addalert-classy](https://cloud.githubusercontent.com/assets/926653/18037599/53390212-6d91-11e6-837e-d1194928871a.gif)

You can read the [addAlert() API docs](https://github.com/TalAter/Progressive-UI-KITT/blob/master/docs/API.md#addalertstring-string-function-object-object).

Add test specs that verify the following:

``` javascript
      describe('ProgressiveKITT.addAlert(text, label, callback, { class: string })', function() {

        it('should add a class to the alert div equal to the value passed as `class` in the settings object (if it is a string)', function () {
        });

        it('should add a class to the alert div equal to the string representation of the value passed as `class` in the settings object (if it is not a string)', function () {
        });

      });
```

This should be added into the file `/test/spec/2_UISpec.js` at the end of the following test suite:

``` javascript
describe('ProgressiveKITT.addAlert', function() {
```

This should be very similar to the tests for `ProgressiveKITT.addMessage(text, { class: string })` which you can find in the same file.
#### Contributing to Progressive UI KITT
- [ ] Fork the repository from the [Progressive UI KITT GitHub page](https://github.com/TalAter/Progressive-UI-KITT).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/Progressive-UI-KITT.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of Progressive UI KITT's development dependencies with npm. `$ cd Progressive-UI-KITT; npm install`
- [ ] Run grunt to make sure everything runs smoothly `$ grunt`
- [ ] Code, code, code.
- [ ] Run `$ grunt` after making changes to verify that everything still works and run the build process. Alternatively, you can just run `$ grunt watch` once, and leave that process running. It will continuously run all the tests and build the files every time you make a change to one of KITT's files. It will even _beep_ if you make an error, and help you debug it.:+1:
- [ ] Before committing your changes, the last step must always be running `$ grunt`. This makes sure everything works, and all files are kept up to date with your changes.
- [ ] Once you've made sure all your changes work correctly, and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/Progressive-UI-KITT](https://github.com/YOUR-USER-NAME/Progressive-UI-KITT)) and create a pull request for your changes.
- [ ] Makes sure your pull request describes exactly what you changed and references this issue (just include the issue number in the title like this: #49)
#### About the tests

Progressive UI KITT is tested using [Jasmine](http://jasmine.github.io/2.0/introduction.html).

`1_BasicSpec.js`, `2_UISpec.js` and `3_CallbackSpec.js` contain a series of spec groups (e.g. `describe('a spec group', function() {})`) which each contain 1 or more specs (e.g. `it('should do stuff', function() {})`). Some of the spec groups also contain some code which runs before each spec (`beforeEach(function() {})`).

**Comment by alavkx** [comment]
First of all, thanks for doing this! I appreciate you taking the time to write out a detailed guide for first timers like myself to get into OSS.
Just a heads up for those who don't already have grunt installed, you will need to install it globally on your machine, as the command line tools no longer come prepackaged with grunt.

So the process for getting started should look like...
`npm install`
`npm install -g grunt-cli` 
then `grunt`  or  `grunt watch` should work.

**Comment by TalAter** [comment]
Thank you for the help @alavkx.

I hope it is the first of many :octocat: open source contributions for you!
